---
- name: 'Docker: Installing dependencies'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: 'Docker: Adding APT key'
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: 'Docker: Adding APT repository'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: 'Docker: Installing APT packages'
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools
    - "{{ docker_package }}"

- name: 'Docker: Replace ExecStart for systemd'
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: '^ExecStart=/usr/bin/dockerd[.]?'
    line: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://{{ ansible_default_ipv4.address }}:2375"

- name: 'Docker: Change MTU value for Openstack deployments'
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: '^ExecStart=/usr/bin/dockerd[.]?'
    line: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://{{ ansible_default_ipv4.address }}:2375 --mtu=1450"
  tags: ['never', 'openstack']

- name: 'Docker: Restart service'
  systemd:
    daemon_reload: yes
    name: docker
    state: restarted
    enabled: yes
    masked: no

- name: 'Docker-compose: Installing python tools'
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
  with_items:
    - python-setuptools
    - python3-pip

- name: 'Docker-compose: Installing pip package manager'
  easy_install:
    name: "{{ docker_compose_pip_version }}"

- name: 'Docker-compose: Install'
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present

- name: 'Docker Swarm: Initialization'
  shell: docker swarm init
        --listen-addr {{ ansible_default_ipv4.address }}
        --advertise-addr {{ ansible_default_ipv4.address }}

- name: 'Docker Swarm: Change manager availability to drain'
  shell: docker node update
        --availability drain {{ micado_master_name }}
