---

- name: Create directory /var/lib/micado/submitter/data/
  file:
    path: /var/lib/micado/submitter/data/
    state: directory
    mode: 0775
    recurse: yes
- name: Create temp_user_data.yaml for Micado submitter
  template:
      src: user_data/temp_user_data.yml.j2
      dest: "/var/lib/micado/submitter/data/temp_user_data.yaml"

- name: "Consul config: Create directory"
  file:
    path: /var/lib/micado/consul/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Consul config: Copy file"
  copy:
    src: consul/config.json
    dest: /var/lib/micado/consul/config/config.json
    mode: 0644
- name: "Consul config: create checks.json"
  template:
    src: consul/checks.json.j2
    dest: /var/lib/micado/consul/config/checks.json
    mode: 0644

- name: "Prometheus config: Create directory"
  file:
    path: /var/lib/micado/prometheus/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Prometheus config: Copy file"
  copy:
    src: prometheus/prometheus.yml
    dest: /var/lib/micado/prometheus/config/prometheus.yml
    mode: 0644

- name: "Alertmanager config: Create directory"
  file:
    path: /var/lib/micado/alertmanager/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Alertmanager config: Copy file"
  copy:
    src: alertmanager/config.yml
    dest: /var/lib/micado/alertmanager/config/config.yml
    mode: 0644

- name: "Policy-keeper config: Create directory"
  file:
    path: /var/lib/micado/policykeeper/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Policy-keeper: Copy config file"
  template:
    src: policykeeper/policykeeper_config.yaml.j2
    dest: /var/lib/micado/policykeeper/config/policykeeper_config.yaml
- name: "Policy-keeper: Copy prometheus file"
  copy:
    src: policykeeper/prometheus_config_template.yaml
    dest: /var/lib/micado/policykeeper/config/prometheus_config_template.yaml
    mode: 0644

- name: "Docker-compose: Copy file"
  template:
    src: docker/docker-compose.yml.j2
    dest: /var/lib/micado/docker-compose.yml
    mode: 0644


