---
- name: "Occopus Credentials: Load the credentials from the playbook"
  include_vars:
    file: "{{ cloud_cred_path }}"
    name: config

- name: "Security Credentials: Load the credentials and security settings from the playbook"
  include_vars:
    file: "{{ micado_cred_path  }}"
    name: security

- name: "Consul config: Create directory"
  file:
    path: /var/lib/micado/consul/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Consul config: Generate encrypton key"
  shell: "tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' < /dev/urandom 2>/dev/null | head -c 16 | base64"
  register: consul_key

- name: "Consul config: Copy file"
  template:
    src: consul/config.json.j2
    dest: /var/lib/micado/consul/config/config.json
    mode: 0644

- name: "Consul config: Create checks.json"
  template:
    src: consul/checks.json.j2
    dest: /var/lib/micado/consul/config/checks.json
    mode: 0644

- name: "Prometheus config: Create directory"
  file:
    path: /var/lib/micado/prometheus/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Prometheus config: Copy file"
  copy:
    src: prometheus/prometheus.yml
    dest: /var/lib/micado/prometheus/config/prometheus.yml
    mode: 0644

- name: "Prometheus data: Create directory"
  file:
    path: /var/lib/micado/prometheus/data/
    state: directory
    owner: nobody
    group: nogroup
    mode: 0775
    recurse: yes

- name: "Alertmanager config: Create directory"
  file:
    path: /var/lib/micado/alertmanager/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Alertmanager config: Copy file"
  copy:
    src: alertmanager/config.yml
    dest: /var/lib/micado/alertmanager/config/config.yml
    mode: 0644

- name: "Policy-keeper config: Create directory"
  file:
    path: /var/lib/micado/policykeeper/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Policy-keeper config: Copy file"
  template:
    src: policykeeper/policykeeper_config.yaml.j2
    dest: /var/lib/micado/policykeeper/config/policykeeper_config.yaml

- name: "Policy-keeper config: Copy prometheus config template"
  copy:
    src: policykeeper/prometheus_config_template.yaml
    dest: /var/lib/micado/policykeeper/config/prometheus_config_template.yaml
    mode: 0644

- name: "Grafana config: Create config directory"
  file:
    path: /var/lib/micado/grafana/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Grafana config: Copy server config file"
  copy:
    src: grafana/grafana.ini
    dest: /var/lib/micado/grafana/config/grafana.ini
    mode: 0644

- name: "Grafana config: Create dashboard directory"
  file:
    path: /var/lib/micado/grafana/data/dashboards
    state: directory
    mode: 0775
    recurse: yes

- name: "Grafana config: Copy dashboard file"
  copy:
    src: grafana/data-dashboards-micado-{{ container_orchestrator }}.json
    dest: /var/lib/micado/grafana/data/dashboards/micado.json
    mode: 0644

- name: "Grafana config: Create dashboard providers directory"
  file:
    path: /var/lib/micado/grafana/provisioning/dashboards
    state: directory
    mode: 0775
    recurse: yes

- name: "Grafana config: Copy dashboard provider file"
  copy:
    src: grafana/provisioning-dashboards-provider.yaml
    dest: /var/lib/micado/grafana/provisioning/dashboards/provider.yaml
    mode: 0644

- name: "Grafana config: Create datasource directory"
  file:
    path: /var/lib/micado/grafana/provisioning/datasources
    state: directory
    mode: 0775
    recurse: yes

- name: "Grafana config: Copy datasource file"
  copy:
    src: grafana/provisioning-datasources-prometheus.yaml
    dest: /var/lib/micado/grafana/provisioning/datasources/prometheus.yaml
    mode: 0644

- name: "TOSCA Submitter config: Create working directory"
  file:
    path: /var/lib/micado/toscasubmitter/system
    state: directory
    mode: 0775
    recurse: yes

- name: "TOSCA Submitter config: Copy config file"
  copy:
    src: toscasubmitter/key_config-{{ container_orchestrator }}.yml
    dest: /var/lib/micado/toscasubmitter/system/key_config.yml
    mode: 0644

- name: "Credential Manager config: Create directory"
  file:
    path: /var/lib/micado/credman/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Credential Manager initial config: Copy file"
  template:
    src: user_data/auth_data_credential_manager.csv.j2
    dest: /var/lib/micado/credman/config/provisioning.csv

- name: "Zorp config: Create directory"
  file:
    path: /var/lib/micado/zorp/config/
    state: directory
    mode: 0775
    recurse: yes

- name: "Zorp config: Copy file"
  copy:
    src: zorp/policy-{{ container_orchestrator }}.py
    dest: /var/lib/micado/zorp/config/policy.py
    mode: 0644

- name: "Zorp HTTP login form: Copy file"
  copy:
    src: zorp/authform.html
    dest: /var/lib/micado/zorp/config/authform.html
    mode: 0644

- name: "Zorp entrypoint: Create directory"
  file:
    path: /var/lib/micado/zorp/scripts/
    state: directory
    mode: 0775
    recurse: yes

- name: "Zorp entrypoint: Copy file"
  copy:
    src: zorp/zorp-entrypoint.sh
    dest: /var/lib/micado/zorp/scripts/docker-entrypoint.sh
    mode: 0755

- name: Create user_data_zorp.env for Zorp
  template:
      src: user_data/user_data_zorp.env.j2
      dest: "/var/lib/micado/zorp/config/user_data_zorp.env"

- name: "Redis logging: Create log directory"
  file:
    path: /var/log/micado/redis/
    state: directory
    mode: 0777
    recurse: yes

- name: "Consul logging: Create log directory"
  file:
    path: /var/log/micado/consul/
    state: directory
    mode: 0775
    recurse: yes

- name: "Consul logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs consul\n"
    dest: /var/log/micado/consul/README
    mode: 0644

- name: "Prometheus logging: Create log directory"
  file:
    path: /var/log/micado/prometheus/
    state: directory
    mode: 0775
    recurse: yes

- name: "Prometheus logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs prometheus\n"
    dest: /var/log/micado/prometheus/README
    mode: 0644

- name: "Alertmanager logging: Create log directory"
  file:
    path: /var/log/micado/alertmanager/
    state: directory
    mode: 0775
    recurse: yes

- name: "Alertmanager logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs alertmanager\n"
    dest: /var/log/micado/alertmanager/README
    mode: 0644

- name: "Dashboard logging: Create log directory"
  file:
    path: /var/log/micado/dashboard/
    state: directory
    mode: 0775
    recurse: yes

- name: "Dashboard logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs micado-dashboard\n"
    dest: /var/log/micado/dashboard/README
    mode: 0644

- name: "Visualizer logging: Create log directory"
  file:
    path: /var/log/micado/visualizer/
    state: directory
    mode: 0775
    recurse: yes
  when: container_orchestrator == 'swarm'

- name: "Visualizer logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs dockervisualizer\n"
    dest: /var/log/micado/visualizer/README
    mode: 0644
  when: container_orchestrator == 'swarm'

- name: "Credential Manager logging: Create log directory"
  file:
    path: /var/log/micado/credman/
    state: directory
    mode: 0775
    recurse: yes

- name: "Credential Manager logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs credman\n"
    dest: /var/log/micado/credman/README
    mode: 0644

- name: "Zorp logging: Create log directory"
  file:
    path: /var/log/micado/zorp/
    state: directory
    mode: 0775
    recurse: yes

- name: "Zorp logging: Create log output info"
  copy:
    content: "Check the logs by the following command:\ndocker logs zorp\n"
    dest: /var/log/micado/zorp/README
    mode: 0644

- name: "Docker-compose: Copy file"
  template:
    src: docker/docker-compose-{{ container_orchestrator }}.yml.j2
    dest: /var/lib/micado/docker-compose.yml
    mode: 0644

- name: "Iptables configuration: Copy file"
  template:
    src: iptables/iptables-{{ container_orchestrator }}.conf.j2
    dest: /etc/iptables.conf
    mode: 0640

- name: "Iptables systemd unit file: Copy file"
  copy:
    src: iptables/iptables.service
    dest: /etc/systemd/system/iptables.service
    mode: 0644

- name: "Ip6tables configuration: Copy file"
  template:
    src: iptables/ip6tables-{{ container_orchestrator }}.conf.j2
    dest: /etc/ip6tables.conf
    mode: 0640

- name: "Ip6tables systemd unit file: Copy file"
  copy:
    src: iptables/ip6tables.service
    dest: /etc/systemd/system/ip6tables.service
    mode: 0644

- name: "MiCADO systemd unit file: Copy file"
  copy:
    src: micado/micado.service
    dest: /etc/systemd/system/micado.service
    mode: 0644

- name: "micadoctl: copy file"
  copy:
    src: misc/micadoctl
    dest: /usr/local/bin/micadoctl
    mode: 0755
