---
# install strongSwan
- name: Install strongSwan
  apt:
    name: strongswan
    state: present
  tags: 'build'

# create configuration
- name: "Create ipsec configuration"
  copy:
    content: |
        config setup
                uniqueids=never

        conn iptunnel
                type=transport
                compress=yes
                fragmentation=yes
                keyexchange=ikev2
                authby=pubkey
                leftid="CN=workernode.micado"
                leftcert=master.crt
                left={{ ansible_default_ipv4.address }}
                right=%any
                auto=start
    dest: /etc/ipsec.conf
  tags: 'start'

