---
- name: "Worker node: Occopus: Create directory"
  file:
    path: /var/lib/micado/occopus/data/
    state: directory
    mode: 0775
    recurse: yes

- name: Create auth_data.yaml for Occopus
  template:
    src: user_data/auth_data.yaml.j2
    dest: "/var/lib/micado/occopus/data/auth_data.yaml"

- name: "Worker node: Occopus nodes: Copy cloud-config"
  copy:
    src: worker_node/cloud_init_worker.yaml
    dest: /var/lib/micado/toscasubmitter/system/cloud_init_worker.yaml
    mode: 0644

- name: "Worker node: Generate Occopus infrastructure descriptor"
  template:
    src: user_data/temp_infrastructure_descriptor.yaml.j2
    dest: /var/lib/micado/toscasubmitter/system/infrastructure_descriptor.yaml
    mode: 0644
