---
- name: '(Kubernetes) Turn off swap'
  command: swapoff -a
  changed_when: False

- name: '(Kubernetes) Disable swap permanently'
  replace:
    mode: '0644'
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'

- name: '(Kubernetes) Add APT key'
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
  register: add_key
  until: add_key is succeeded
  retries: 5
  delay: 15

- name: '(Kubernetes) Add APT repository'
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: 'kubernetes'
    mode: '0600'

- name: '(Kubernetes) Install APT packages'
  apt:
    name:
    - kubelet={{ packages.kubernetes_version }}
    - kubeadm={{ packages.kubernetes_version }}
    - kubectl={{ packages.kubernetes_version }}
    state: present
    update_cache: yes

- name: '(Kubernetes) prevent package from being upgraded'
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubeadm
  - kubectl