prometheus_endpoint: 'http://prometheus:9090/prometheus'
prometheus_config_template: '/config/policykeeper/prometheus_config_template.yaml'
prometheus_config_target: '/config/prometheus/prometheus.yml'
prometheus_rules_directory: '/config/prometheus'

docker_node_unreachable_timeout: 120

k8s_endpoint: 'unix:///var/run/docker.sock'

occopus_endpoint: 'http://occopus:5000'
occopus_infra_name: 'micado_worker_infra'
occopus_worker_name: 'worker'

optimizer_endpoint: 'http://optimizer:12346'

optimizer_vars_prefix_init: 'm_opt_init_'
optimizer_vars_prefix_input: 'm_opt_input_'
optimizer_vars_prefix_target: 'm_opt_target_'
optimizer_vars_prefix_target_query: 'query_'
optimizer_vars_prefix_target_minth: 'minth_'
optimizer_vars_prefix_target_maxth: 'maxth_'

logging:
    version: 1
    root:
        level: DEBUG
        handlers: [console, file]
    formatters:
        simpleFormatter:
            #format: "%(module)s %(asctime)s %(levelname)s %(message)s"
            format: "%(asctime)s %(levelname)s %(message)s"
        usercodeFormatter:
            format: "%(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormatter
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.handlers.RotatingFileHandler
            formatter: simpleFormatter
            mode: a
            level: DEBUG
            filename: /var/log/policykeeper/pk.log
            maxBytes: 52428800
            backupCount: 3
        file_usercode:
            class : logging.handlers.RotatingFileHandler
            formatter: usercodeFormatter
            mode: a
            level: DEBUG
            filename: /var/log/policykeeper/pk_usercode.log
            maxBytes: 52428800
            backupCount: 3
    loggers:
        pk:
            propagate: false
            handlers: [console, file]
        pk_k8s:
            propagate: false
            handlers: [console, file]
        pk_prometheus:
            propagate: true
            handlers: [console, file]
        pk_optimizer:
            propagate: false
            handlers: [console, file]
        pk_usercode:
            propagate: false
            handlers: [file_usercode]
