---
- name: Create components directory
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0775
    state: directory
  loop:
    - { path: '/var/lib/micado/alertmanager/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/alertmanager/data/', owner: 'nobody', group: 'nogroup' }
    - { path: '/var/lib/micado/credman/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/crypto_engine/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/grafana/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/grafana/data/dashboards', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/grafana/provisioning/datasources', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/grafana/provisioning/dashboards', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/grafana/provisioning/notifiers', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/occopus/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/occopus/data/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/optimizer/config', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/optimizer/data', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/policykeeper/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/prometheus/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/prometheus/data/', owner: 'nobody', group: 'nogroup' }
    - { path: '/var/lib/micado/redis/data/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/toscasubmitter/system', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/vault/config', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/vault/storage', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/zorp/config/', owner: 'root', group: 'root' }
    - { path: '/var/lib/micado/zorp/scripts/', owner: 'root', group: 'root' }
    # Logs
    - { path: '/var/log/micado/alertmanager/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/credman/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/crypto_engine/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/dashboard/',owner: 'root', group: 'root' }
    - { path: '/var/log/micado/grafana/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/iivr/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/occopus/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/optimizer/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/policykeeper/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/prometheus/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/redis/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/toscasubmitter/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/zorp/', owner: 'root', group: 'root' }
    - { path: '/var/log/micado/vault/', owner: 'root', group: 'root' }

- name: Copy components config file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: 'alertmanager/config.yml', dest: '/var/lib/micado/alertmanager/config/alertmanager.yml', mode: '0644'}
    - { src: 'grafana/grafana.ini', dest: '/var/lib/micado/grafana/config/grafana.ini', mode: '0644'}
    - { src: 'grafana/data-dashboards-micado.json', dest: '/var/lib/micado/grafana/data/dashboards/micado.json', mode: '0644'}
    - { src: 'grafana/provisioning-dashboards-provider.yaml', dest: '/var/lib/micado/grafana/provisioning/dashboards/provider.yaml', mode: '0644'}
    - { src: 'grafana/provisioning-datasources-prometheus.yaml', dest: '/var/lib/micado/grafana/provisioning/datasources/prometheus.yaml', mode: '0644'}
    - { src: 'iptables/iptables.service', dest: '/etc/systemd/system/iptables.service', mode: '0644'}
    - { src: 'iptables/ip6tables.service', dest: '/etc/systemd/system/ip6tables.service', mode: '0644'}
    - { src: 'micado/micado.service', dest: '/etc/systemd/system/micado.service', mode: '0644'}
    - { src: 'misc/micadoctl', dest: '/usr/local/bin/micadoctl', mode: '0755'}
    - { src: 'occopus/occopus_config.yaml', dest: '/var/lib/micado/occopus/config/occopus_config.yaml', mode: '0775'}
    - { src: 'policykeeper/policykeeper_config.yaml', dest: '/var/lib/micado/policykeeper/config/policykeeper_config.yaml', mode: '0644'}
    - { src: 'prometheus/prometheus.yml', dest: '/var/lib/micado/prometheus/config/prometheus.yml', mode: '0644'}
    - { src: 'toscasubmitter/key_config.yml', dest: '/var/lib/micado/toscasubmitter/system/key_config.yml', mode: '0644'}
    - { src: 'vault/vault.hcl', dest: '/var/lib/micado/vault/config/vault.hcl', mode: '0644'}
    - { src: 'zorp/authform.html', dest: '/var/lib/micado/zorp/config/authform.html', mode: '0644'}
    - { src: 'zorp/zorp-entrypoint.sh', dest: '/var/lib/micado/zorp/scripts/docker-entrypoint.sh', mode: '0755'}

- name: "Copy log README file"
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep alertmanager | col1)\n', dest: '/var/log/micado/alertmanager/README'}
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep credman | col1)\n', dest: '/var/log/micado/credman/README'}
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep crypto-engine | col1)\n', dest: '/var/log/micado/crypto_engine/README'}
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep iivr | col1)\n', dest: '/var/log/micado/iivr/README'}
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep micado-dashboard | col1)\n', dest: '/var/log/micado/dashboard/README'}
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep prometheus | col1)\n', dest: '/var/log/micado/prometheus/README'}
    - { content: 'Check the logs by the following command:\nkubectl -n micado-system logs $(kubectl -n micado-system get pod | grep zorp | col1)\n', dest: '/var/log/micado/zorp/README'}
