---
- name: Install pip package manager
  apt:
    name:
    - python-setuptools
    - python3-pip
    state: present

- name: 'Security: Install strongSwan'
  apt:
    name: strongswan
    state: present

- name: Installing Python packages
  pip:
    name:
    - docker
    - requests
    - click
    - terminaltables
    - pyyml
    state: present
